# 配置是没有使用数据库连接池的
server:
  port: 80
spring:
  redis:
    database: 5      # 默认是0
    host: localhost
    port: 6379
    password:        # 默认是null
    lettuce:
      pool:
        max-active: 8
        max-wait: -1   # 默认-1 最大阻塞等待时间
        max-idle: 2    # 最大空闲链接数
        min-idle: 1    # 最小空闲连接数
