spring:
  redis:
    host: 192.168.88.128
    port: 6381
    password:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
    sentinel:
      master: mymaster
      nodes:
        - 192.168.88.128:26379
        - 192.168.88.128:26380
